export const products = [
  {
    id: 1,
    link: "https://restaurant-site.pages.dev/",
    github: "",
    title: "Simple Restaurant Site",
    desc: "A simple yet stylish restaurant site is built with the latest HTML, JS, and CSS technology, providing a seamless and user-friendly interface. ",
    tech: ["javascript", "html", "css"],
  },
  {
    id: 2,
    link: "https://frimps-edu.pages.dev/",
    github: "",
    title: "Educational Site",
    desc: "An innovative and interactive educational platform is crafted with cutting-edge HTML, JS, and CSS technology, delivering a seamless and engaging user experience. ",
    tech: ["javascript", "html", "css"],
  },
  {
    id: 3,
    link: "https://the-kwame-inc-site.pages.dev/",
    github: "",
    title: "The Kwame Inc",
    desc: "A stylish and functional framing website created with React, boasting a seamless and intuitive user interface, aimed at attracting and engaging more customers.",
    tech: ["react", "css"],
  },
  {
    id: 4,
    link: "https://frimps-edu.pages.dev/",
    github: "",
    title: "Simple Restaurant Site",
    desc: "A simple yet attractive framing site is built with react, providing a seamless and user-friendly interface. ",
    tech: ["React", "css"],
  },
  {
    id: 5,
    link: "http://lama.dev",
    github: "",
    title: "Simple Restaurant Site",
    desc: "A simple yet stylish restaurant site is built with the latest HTML, JS, and CSS technology, providing a seamless and user-friendly interface. ",
    tech: ["javascript", "html", "css"],
  },
  {
    id: 6,
    link: "http://lama.dev",
    github: "",
    title: "Simple Restaurant Site",
    desc: "A simple yet stylish restaurant site is built with the latest HTML, JS, and CSS technology, providing a seamless and user-friendly interface. ",
    tech: ["javascript", "html", "css"],
  },
];
